export const data = { projectsList: [
    {
        id: 1,
        name: 'Internal project #1',
        creationDate: '2019-01-16',
    },
    {
        id: 2,
        name: 'GENERAL',
        creationDate: '2018-01-16',
    },
    {
        id: 3,
        name: 'Test Project',
        creationDate: '2018-08-19',
    },
    {
        id: 4,
        name: 'Face Recognition App',
        creationDate: '2017-02-18',
    },
    {
        id: 5,
        name: 'Top Visuals',
        creationDate: '2017-03-17',
    },
    {
        id: 6,
        name: 'Akvelon Inc stats',
        creationDate: '2020-01-20',
    },
],
tasksList : [
    {
        id: 1,
        parentProjectId: 1,
        name: 'schedule meeting',
        description: 'new teammate onboard meeting',
        estimate: 2,
        creationDate: '2018-01-16',
    },
    {
        id: 2,
        parentProjectId: 1,
        name: 'fix bug',
        description: 'unexpected behavior on...',
        estimate: 4,
        creationDate: '2018-01-16',
    },
    {
        id: 3,
        parentProjectId: 2,
        name: 'create git repo',
        description: 'create repo, give access to ....',
        estimate: 2,
        creationDate: '2018-03-04',
    },
    {
        id: 4,
        parentProjectId: 2,
        name: 'log work',
        description: 'log all forgotten work hours',
        estimate: 1,
        creationDate: '2019-03-04',
    },
    {
        id: 5,
        parentProjectId: 2,
        name: 'fix bug',
        description: 'unexpected behavior on...',
        estimate: 4,
        creationDate: '2019-03-08',
    },
    {
        id: 6,
        parentProjectId: 2,
        name: 'count opened issues',
        description: 'close if solved ',
        estimate: 3,
        creationDate: '2019-03-08',
    },
    {
        id: 7,
        parentProjectId: 3,
        name: 'log work',
        description: 'log all forgotten work hours',
        estimate: 8,
        creationDate: '2019-07-15',
    },
    {
        id: 8,
        parentProjectId: 3,
        name: 'implement task #233432545',
        description: 'take some time for investigation if needed',
        estimate: 1,
        creationDate: '2017-07-15',
    },
    {
        id: 9,
        parentProjectId: 3,
        name: 'create git repo',
        description: 'create repo, give access to ....',
        estimate: 3,
        creationDate: '2017-07-15',
    },
    {
        id: 10,
        parentProjectId: 3,
        name: 'implement task #22545',
        description: 'close if solved',
        estimate: 3,
        creationDate: '2017-09-10',
    },
    {
        id: 11,
        parentProjectId: 4,
        name: 'implement task #233545',
        description: 'take some time for investigation if needed',
        estimate: 3,
        creationDate: '2019-09-10',
    },
    {
        id: 12,
        parentProjectId: 4,
        name: 'fix bug',
        description: 'unexpected behavior on...',
        estimate: 10,
        creationDate: '2017-10-12',
    },
    {
        id: 13,
        parentProjectId: 4,
        name: 'count opened issues',
        description: 'close if solved ',
        estimate: 10,
        creationDate: '2019-10-12',
    },
    {
        id: 14,
        parentProjectId: 1,
        name: 'implement task #8565',
        description: 'take some time for investigation if needed',
        estimate: 1,
        creationDate: '2020-10-12',
    },
    {
        id: 15,
        parentProjectId: 5,
        name: 'create git repo',
        description: 'create repo, give access to ....',
        estimate: 1,
        creationDate: '2020-02-27',
    },
    {
        id: 16,
        parentProjectId: 5,
        name: 'big issue',
        description: 'big issue description...',
        estimate: 1,
        creationDate: '2019-02-27',
    },
    {
        id: 17,
        parentProjectId: 2,
        name: 'code refactoring',
        description: 'inspect code to find possible issues ....',
        estimate: 1,
        creationDate: '2020-02-27',
    },
    {
        id: 18,
        parentProjectId: 5,
        name: 'fix bug',
        description: 'unexpected behavior - steps to reproduce...',
        estimate: 1,
        creationDate: '2019-02-27',
    },
    {
        id: 19,
        parentProjectId: 6,
        name: 'log work',
        description: 'log all forgotten work hours',
        estimate: 1,
        creationDate: '2020-02-27',
    },
    {
        id: 20,
        parentProjectId: 6,
        name: 'count opened issues',
        description: 'close if solved ',
        estimate: 6,
        creationDate: '2019-01-16',
    },
    {
        id: 21,
        parentProjectId: 6,
        name: 'implement task #29655',
        description: 'write weekly report to the client',
        estimate: 2,
        creationDate: '2019-01-16',
    },
    {
        id: 22,
        parentProjectId: 6,
        name: 'create git repo',
        description: 'create repo, give access to ....',
        estimate: 5,
        creationDate: '2019-01-16',
    },
]
}